---
language: node_js

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: bdw+L6W3VybnRnCrbYraAt8uQVRuRcJuI/zM5b80Qsv/DAPgedUV5ii7bMYhUe0ebBd7nwjPF62gkBi9zsFO2L9qBSH65smyInXHclmxefvfZY7VXq9d01BNwJpFuoZ9oeSd7NHmNi0P4QJHLqGLN/NELYWWSvlwoTlt+i7GPJw=
  app: my-music-client
  on:
    repo: Dremora/my-music-client
